# Generated by Django 4.1 on 2024-06-22 15:27

import account.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", account.models.CustomUserManager()),
            ],
        ),
    ]
